apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  postgres-init.sh: |-
{{ .Files.Get "files/postgres-init.sh" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |-
{{ .Files.Get "files/kong.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
{{ .Files.Get "files/prometheus.yml" | indent 4 }}
