_format_version: "3.0"
_transform: true

services:
  - name: user-service
    url: http://user-service:3000
    routes:
      - name: user-register-route
        paths:
          - /users
        methods:
          - POST
        strip_path: false
      - name: user-login-route
        paths:
          - /login
        methods:
          - POST
        strip_path: false
      - name: user-protected-routes
        paths:
          - /users
        methods:
          - GET
        strip_path: false
        plugins:
          - name: jwt
      - name: user-fund-route
        paths:
          - ~/users/\d+/fund
        methods:
          - POST
        strip_path: false
        plugins:
          - name: jwt
      - name: user-docs-route
        paths:
          - /docs/users
        methods:
          - GET
        strip_path: false

  - name: payment-processor
    url: http://payment-processor:3001
    routes:
      - name: payment-routes
        paths:
          - /payments
        strip_path: false
        plugins:
          - name: jwt
      - name: payment-docs-route
        paths:
          - /docs/payments
        methods:
          - GET
        strip_path: false

  - name: ledger-service
    url: http://ledger-service:3002
    routes:
      - name: ledger-routes
        paths:
          - /ledger
        strip_path: false
        plugins:
          - name: jwt
      - name: ledger-docs-route
        paths:
          - /docs/ledger
        methods:
          - GET
        strip_path: false

plugins:
  - name: prometheus

  - name: rate-limiting
    # Global rate limit of 100 requests per minute per IP
    enabled: true
    config:
      minute: 100
      policy: local

consumers:
  - username: test-consumer
    jwt_secrets:
      - key: "kong-issuer"
        secret: "my-super-secret-key"
        algorithm: "HS256"
